package com.mirror.bench;

import java.util.function.LongSupplier;

/** Debug-only asynchronous EXT timer queries. No Android/JSON dependencies and no GL calls when off.
 * Sole reader of GPU_DISJOINT_EXT for this context. All mutating calls belong to one GL owner.
 * No query nesting, waits, fences, finish or flush. Poll only once on a later callback.
 * GPU elapsed is completion-timeline duration, NOT exclusive engine occupancy or presentation time.
 */
public final class GpuTimerProbe {
    public static final int SLOTS=16,HISTORY=128,DEFAULT_SAMPLE_EVERY=8;
    public enum Stage { VIEWS_ALL, INTERLACE_WITH_BACKGROUND, BACKGROUND_GEOMETRY }
    public enum Status { VALID,DISJOINT,INVALID_RESULT,TIMEOUT_OR_OVERFLOW,POOL_FULL,ABORTED,DRIVER_ERROR,CONTEXT_LOST,CLOSED }
    /** A GL error might have been generated by an earlier avatar command. Never silently consume it. */
    public static final class GlFailure extends IllegalStateException {
        public final int errorCode;
        public GlFailure(int code,String operation){super("GPU probe observed GL 0x"+Integer.toHexString(code)+" at "+operation+"; origin may precede probe");errorCode=code;}
    }
    public interface Driver {
        /** 0 means unsupported; implementation checks extension and all required function pointers. */
        int counterBits();
        boolean currentContext();
        int[] create(int count);
        boolean disjoint();
        void begin(int query);
        void end();
        boolean available(int query);
        /** Recheck availability, fetch QUERY_RESULT as unsigned32, widen without sign extension. */
        long result(int query);
        void delete(int[] queries);
    }
    public static final class Event {
        public final long sequence,contextGeneration,scopeEpoch,frameId,submittedCpuNs,resolvedCpuNs,gpuNs;
        public final Stage stage;public final Status status;
        private Event(Slot s,long generation,long resolved,Status status){
            sequence=s.sequence;contextGeneration=generation;scopeEpoch=s.epoch;frameId=s.frame;submittedCpuNs=s.started;
            resolvedCpuNs=resolved;stage=s.stage;this.status=status;gpuNs=status==Status.VALID?s.value:-1;
        }
    }
    public static final class Snapshot {
        public final boolean requested;public final String state,error;public final int counterBits,pending,tombstones,sampleEvery;
        public final long generation,poolFull,historyOverwritten,disjointChecks,disjointEvents;
        public final long[] validCounts,missingCounts;public final double[] totalGpuNs;public final Event[] events;
        private Snapshot(GpuTimerProbe p){
            requested=p.requested;state=p.state;error=p.error;counterBits=p.bits;pending=p.pendingCount();sampleEvery=p.every;
            tombstones=p.tombstoneCount();
            generation=p.generation;poolFull=p.poolFull;historyOverwritten=p.overwritten;disjointChecks=p.disjointChecks;disjointEvents=p.disjointEvents;
            validCounts=p.valid.clone();missingCounts=p.missing.clone();totalGpuNs=p.total.clone();
            events=new Event[p.eventCount];for(int i=0;i<events.length;i++){
                int q=(p.eventWrite-p.eventCount+i+HISTORY)%HISTORY;
                events[i]=new Event(p.eventSlots[q],generation,p.eventResolved[q],p.eventStatus[q]);
            }
        }
    }
    private static final class Slot {
        int state;long frame,epoch,started,token,value,sequence;Stage stage;Status rejected;
        void copy(Slot s){frame=s.frame;epoch=s.epoch;started=s.started;stage=s.stage;value=s.value;}
    }
    private final Thread owner=Thread.currentThread();
    private final Driver driver;private final LongSupplier clock;private final boolean requested;
    private final long generation;private final int every;
    private final Slot[] slots=new Slot[SLOTS],eventSlots=new Slot[HISTORY];
    private final boolean[] ready=new boolean[SLOTS];
    private final long[] eventResolved=new long[HISTORY],valid=new long[3],missing=new long[3];
    private final Status[] eventStatus=new Status[HISTORY];private final double[] total=new double[3];
    private int[] queries;private int bits,active=-1,eventWrite,eventCount;
    private long maxAgeNs,nextToken,eventSequence,poolFull,overwritten,disjointChecks,disjointEvents,lastPollFrame=-1,lastFrame=-1;
    private String state,error="";private boolean closed,abandoned;

    public GpuTimerProbe(boolean requested,long generation,Driver driver,LongSupplier clock,int sampleEvery){
        if(generation<1||clock==null||sampleEvery<1||sampleEvery>120||(requested&&driver==null))throw new IllegalArgumentException("Invalid GPU timer configuration");
        this.requested=requested;this.generation=generation;this.driver=driver;this.clock=clock;every=sampleEvery;
        for(int i=0;i<SLOTS;i++)slots[i]=new Slot();for(int i=0;i<HISTORY;i++)eventSlots[i]=new Slot();
        state=requested?"initializing":"disabled";if(!requested)return;
        try{
            if(!driver.currentContext()){state="unsupported";error="No current creating context";return;}
            bits=driver.counterBits();if(bits<30||bits>64){state="unsupported";error="No usable EXT elapsed counter";return;}
            // 500 ms is below BOTH the minimum 30-bit timer range and unsigned32 result range.
            // Only publish GPU results strictly inside the enclosing host interval; CPU is a
            // validity bound, never the reported GPU duration. This prevents wrap/saturation.
            maxAgeNs=500_000_000L;
            queries=driver.create(SLOTS);if(queries==null||queries.length!=SLOTS)throw new IllegalStateException("Incorrect query pool");
            for(int i=0;i<SLOTS;i++){if(queries[i]==0)throw new IllegalStateException("Zero query id");for(int j=0;j<i;j++)if(queries[i]==queries[j])throw new IllegalStateException("Duplicate query id");}
            readDisjoint();state="active";
        }catch(RuntimeException failure){state="failed";setError(failure);rethrowFirstGl(failure,cleanupQueries());}
    }
    /** Use one monotonically increasing callback id; capture input/config/state epoch at submission.
     * A zero token means not sampled/unavailable; end(0) is a no-op. Never wrap existing CPU work as GPU.
     */
    public long begin(Stage stage,long frameId,long scopeEpoch){
        requireOwner();if(stage==null||frameId<0||scopeEpoch<0)throw new IllegalArgumentException("Stage/frame/epoch required");
        if(!usable())return 0;if(frameId<lastFrame)throw new IllegalArgumentException("Callback id moved backwards");lastFrame=frameId;
        if(active>=0)throw new IllegalStateException("Elapsed queries must not nest");
        if(frameId%every!=0)return 0;
        long now=clock.getAsLong();int free=-1;for(int i=0;i<SLOTS;i++)if(slots[i].state==0){free=i;break;}
        if(free<0){poolFull++;Slot e=eventSlots[eventWrite];e.frame=frameId;e.epoch=scopeEpoch;e.started=now;e.stage=stage;e.value=0;publish(e,now,Status.POOL_FULL);return 0;}
        if(nextToken==Long.MAX_VALUE){fail(Status.DRIVER_ERROR,"GPU timer token exhausted",now);return 0;}
        Slot s=slots[free];s.frame=frameId;s.epoch=scopeEpoch;s.started=now;s.stage=stage;s.rejected=null;s.value=0;s.token=++nextToken;
        s.state=1;active=free;
        try{driver.begin(queries[free]);return s.token;}
        catch(RuntimeException failure){fail(Status.DRIVER_ERROR,failure.toString(),now);propagateGl(failure);return 0;}
    }
    public void end(long token){finish(token,false);}
    public void abort(long token){finish(token,true);}
    private void finish(long token,boolean aborted){
        requireOwner();if(token==0)return;if(active<0||slots[active].token!=token)throw new IllegalArgumentException("Stale GPU timer token");
        if(!contextValid())return;Slot s=slots[active];
        try{driver.end();s.state=2;if(aborted)s.rejected=Status.ABORTED;active=-1;}
        catch(RuntimeException failure){fail(Status.DRIVER_ERROR,failure.toString(),clock.getAsLong());propagateGl(failure);}
    }
    /** Fixed <=16 availability checks/callback, none on queries submitted in this same callback.
     * Two disjoint checks bracket tentative result reads; publish only after the final check.
     * Pending invalidated queries stay quarantined until available, so no query can be overwritten.
     */
    public void poll(long callbackId){
        requireOwner();if(callbackId<0)throw new IllegalArgumentException("Negative callback id");if(!usable())return;
        if(active>=0)throw new IllegalStateException("Poll outside measured scopes");
        if(callbackId<lastPollFrame)throw new IllegalArgumentException("Poll callback moved backwards");if(callbackId==lastPollFrame)return;lastPollFrame=callbackId;
        if(pendingCount()==0)return;
        try{
            if(readDisjoint())rejectPending(Status.DISJOINT);
            long now=clock.getAsLong();
            for(int i=0;i<SLOTS;i++){
                ready[i]=false;Slot s=slots[i];if(s.state<2||s.frame>=callbackId)continue;
                if(s.state==3){ready[i]=driver.available(queries[i]);continue;}
                if(now<s.started||now-s.started>=maxAgeNs){publish(s,now,Status.TIMEOUT_OR_OVERFLOW);s.state=3;continue;}
                ready[i]=driver.available(queries[i]);
                if(ready[i]&&s.rejected==null)s.value=driver.result(queries[i]);
            }
            if(readDisjoint())rejectPending(Status.DISJOINT);
            now=clock.getAsLong();
            for(int i=0;i<SLOTS;i++)if(ready[i]){
                Slot s=slots[i];Status reason=s.rejected;
                if(s.state==3){s.state=0;continue;}
                if(now<s.started||now-s.started>=maxAgeNs)reason=Status.TIMEOUT_OR_OVERFLOW;
                if(reason==null&&(s.value<0||s.value==0xffffffffL||s.value>=maxAgeNs||s.value>=now-s.started))reason=Status.INVALID_RESULT;
                publish(s,now,reason==null?Status.VALID:reason);s.state=0;
            }
        }catch(RuntimeException failure){fail(Status.DRIVER_ERROR,failure.toString(),clock.getAsLong());propagateGl(failure);}
    }
    /** GL-owner only: copy at bounded reporting cadence, then publish the detached snapshot through
     * a caller-owned volatile reference. Status/UI threads must never call this object or wait on GL.
     * No Java monitor spans GL calls. Snapshot arrays belong to the consumer, not this probe. */
    public Snapshot snapshot(){requireOwner();return new Snapshot(this);}
    /** Owner callback after context loss; deliberately makes NO GL calls or deletes. */
    public void abandonContext(){requireOwner();abandon();}
    public void close(){
        requireOwner();if(closed)return;closed=true;if(!requested)return;
        if(abandoned)return;
        if(!driver.currentContext()){abandon();return;}
        RuntimeException endFailure=null;
        if(active>=0){try{driver.end();}catch(RuntimeException failure){setError(failure);endFailure=failure;}if(slots[active].state==1)slots[active].state=2;active=-1;}
        fail(Status.CLOSED,"",clock.getAsLong());RuntimeException cleanupFailure=cleanupQueries();state="closed";
        rethrowFirstGl(endFailure,cleanupFailure);
    }
    private boolean usable(){return !closed&&state.equals("active")&&contextValid();}
    private boolean contextValid(){if(driver.currentContext())return true;abandon();return false;}
    private void abandon(){abandoned=true;fail(Status.CONTEXT_LOST,"Context no longer current; old query IDs abandoned",clock.getAsLong());queries=null;state="context_lost";}
    private void rejectPending(Status reason){for(Slot s:slots)if(s.state!=0&&s.rejected==null)s.rejected=reason;}
    private boolean readDisjoint(){disjointChecks++;boolean d=driver.disjoint();if(d)disjointEvents++;return d;}
    private int pendingCount(){int n=0;for(Slot s:slots)if(s.state!=0)n++;return n;}
    private int tombstoneCount(){int n=0;for(Slot s:slots)if(s.state==3)n++;return n;}
    private void fail(Status reason,String message,long now){
        // If begin/end failed, query activity is uncertain. Retain its ID until close, and attempt
        // one EndQuery there. No further measurements are submitted after this latch.
        for(Slot s:slots)if(s.state!=0){if(s.state!=3)publish(s,now,reason);s.state=0;}
        state=reason==Status.CONTEXT_LOST?"context_lost":"failed";
        if(!message.isEmpty())error=message.length()>240?message.substring(0,240):message;
    }
    private void publish(Slot s,long now,Status status){
        int stage=s.stage.ordinal();if(status==Status.VALID){valid[stage]++;total[stage]+=s.value;}else missing[stage]++;
        eventSlots[eventWrite].copy(s);eventSlots[eventWrite].sequence=++eventSequence;eventResolved[eventWrite]=now;eventStatus[eventWrite]=status;
        eventWrite=(eventWrite+1)%HISTORY;if(eventCount<HISTORY)eventCount++;else overwritten++;
    }
    private RuntimeException cleanupQueries(){
        RuntimeException error=null;
        if(queries!=null){try{if(driver.currentContext())driver.delete(queries);}catch(RuntimeException failure){setError(failure);error=failure;}queries=null;}
        return error;
    }
    private static void rethrowFirstGl(RuntimeException first,RuntimeException cleanup){
        if(first instanceof GlFailure){if(cleanup!=null&&cleanup!=first)first.addSuppressed(cleanup);throw first;}
        if(cleanup instanceof GlFailure){if(first!=null&&first!=cleanup)cleanup.addSuppressed(first);throw cleanup;}
    }
    private void setError(RuntimeException failure){if(!error.isEmpty())return;String s=failure.toString();error=s.length()>240?s.substring(0,240):s;}
    private static void propagateGl(RuntimeException failure){if(failure instanceof GlFailure)throw failure;}
    private void requireOwner(){if(Thread.currentThread()!=owner)throw new IllegalStateException("GPU query belongs to creating GL thread");}
}
